### PR TITLE
Fixed makeDataForView still ising cache when cacheView is set to false

### PR DESCRIPTION
**Pull request by lesichkovm**
This fixes an issue when widget does not render completely even though cacheView is set to false.

Issue shows up when trying to work with updated data like changed cookies or session variables.

### CODE REVIEW

**Comment by imanghafoori1** [comment]
I can not see why and how this change solves the issue.
have you tested it ? (by tampering with the code in the vendor folder)

**Comment by lesichkovm** [comment]
Hi Iman, yes this is exactly how I have tested it. I am using it on a project with over 30 widgets and teh change works like a charm.

**Comment by imanghafoori1** [comment]
Please use the dev-master version, I removed the entire if/else block and I think that should do the job.

You can also do it by hand in the vendor folder:
`WidgetRenderer.php`

before:
```php
if ($widget->cacheView) {
     $this->_viewData = $expensiveCode();
} else {
     $this->_viewData = resolve(Cache::class)->cacheResult($args, $expensiveCode, $widget, 'dataProvider');
}
```

after :

```php
    $this->_viewData = resolve(Cache::class)->cacheResult($args, $expensiveCode, $widget, 'dataProvider');
```

**Comment by imanghafoori1** [comment]
I would be glad if you also install and report any problems with the new laravel-microscope man.

**Comment by lesichkovm** [comment]
Checked it with your suggestion but still caches the data and uses the cache.

`$this->_viewData = resolve(Cache::class)->cacheResult($args, $expensiveCode, $widget, 'dataProvider');`

This is what works. Debug bar added for debugging purposes only. Not really needed.

```
if ($widget->cacheView == false) {
    if (app()->offsetExists('debugbar')) {
        app('widgetize.debugger')->addMessage('Widget' . get_class($widget) . ' making data...');
     }
     $this->_viewData = $expensiveCode();
     return;
}
        
if (app()->offsetExists('debugbar')) {
    app('widgetize.debugger')->addMessage('Widget' . get_class($widget) . ' returning cached data...');
}

// We first try to get the output from the cache before trying to run the expensive $expensiveCode...
$this->_viewData = resolve(Cache::class)->cacheResult($args, $expensiveCode, $widget, 'dataProvider');
```

**Comment by imanghafoori1** [comment]
ok, I accept your changes and review them later.
and only after the review I release the new version.

Remember when you set the cache time to zero or disable it globally, nothing is cached. even if you set the $cacheView=true;

**Comment by imanghafoori1** [comment]
It seems that your implementation is wrong.
I reverted it back and it started to work as expected.

**Pull request merged**
